from abc import ABC, abstractmethod
from pathlib import Path

class IFileSystem(ABC):
    @abstractmethod
    def list_dirs(self, root: Path) -> list[Path]: ...
    @abstractmethod
    def list_files(self, root: Path) -> list[Path]: ...
    @abstractmethod
    def create_dir(self, path: Path) -> None: ...
    @abstractmethod
    def delete_dir_if_empty(self, path: Path) -> bool: ...
    @abstractmethod
    def move(self, src: Path, dst: Path) -> None: ...
    @abstractmethod
    def exists(self, path: Path) -> bool: ...
    @abstractmethod
    def delete_file(self, path: Path) -> None: ...
